# Generated by Django 5.2.14 on 2026-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_performance_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
