# Generated by Django 5.2.14 on 2026-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
