# Generated by Django 5.2.14 on 2026-08-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_task_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, help_text='Real hire date; used for casual leave accrual', null=True),
        ),
    ]
