# Generated by Django 5.2.14 on 2026-08-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employee_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
