# Generated by Django 5.2.14 on 2026-08-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_performance_overall_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('onleave', 'On Leave'), ('relieved', 'Relieved')], default='active', max_length=20),
        ),
    ]
