# Generated by Django 5.2.14 on 2026-09-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='flexible_location',
            field=models.BooleanField(default=False, help_text='Let this employee mark attendance from anywhere, ignoring the work location'),
        ),
    ]
