# Generated by Django 5.2.14 on 2026-07-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
