# Generated by Django 5.2.14 on 2026-08-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_external_ref'),
        ('employees', '0014_alter_performance_overall_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(help_text="The engineer's name exactly as the other system sends it (case-insensitive).", max_length=150, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='The Payroll employee those cases belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='external_aliases', to='employees.employee')),
            ],
            options={
                'verbose_name_plural': 'Engineer aliases',
                'ordering': ['external_name'],
            },
        ),
    ]
