# Generated by Django 5.2.14 on 2026-08-08 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_engineeralias'),
        ('employees', '0014_alter_performance_overall_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('auto_closed', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_sessions', to='employees.employee')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['engineer', 'ended_at'], name='cases_dutys_enginee_a9d52a_idx')],
            },
        ),
    ]
