# Generated by Django 5.2.14 on 2026-08-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_dutysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='completion_source',
            field=models.CharField(blank=True, choices=[('engineer', 'Engineer closed it in the field'), ('upstream', 'Reported closed by the originating system')], default='', help_text='Empty unless the case is completed.', max_length=20),
        ),
    ]
