# Generated by Django 5.2.14 on 2026-08-13 09:50

from django.db import migrations, models


def clear_flag_on_finished_synced_cases(apps, schema_editor):
    """Existing rows default to in_current_plan=True, which is right for the ones
    engineers are working on — they stay visible with no gap at deploy.

    It is wrong for finished ones: every case ever synced and closed would
    suddenly appear on an engineer's list. Those start False instead, and the
    next sync (within five minutes) sets the flag back on any that really are in
    today's plan. Manually-created cases (no external_ref) are left alone.
    """
    Case = apps.get_model("cases", "Case")
    Case.objects.exclude(external_ref="").filter(
        status__in=["completed", "cancelled"]
    ).update(in_current_plan=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_dutysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='in_current_plan',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(
            clear_flag_on_finished_synced_cases,
            migrations.RunPython.noop,
        ),
    ]
