# Generated by Django 5.2.14 on 2026-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_in_current_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
