# Generated by Django 5.2.14 on 2026-08-14 05:39

from django.db import migrations, models
from django.db.models.functions import Coalesce, TruncDate


def backfill_plan_date(apps, schema_editor):
    """Give every already-synced case the day it belongs to.

    A null plan_date means "no plan owns this", which the engineer's list treats
    as always-visible — right for a case created by hand in Payroll, wrong for the
    synced backlog, which would then never age out. Dating them puts each on its
    real day: yesterday's drop off immediately, today's keep showing, and the next
    sync re-stamps whatever is genuinely still in the plan.

    assigned_at is the day that matters, but some rows never got one, so
    created_at stands in — every row has that, and leaving even a few undated
    would keep them on an engineer's screen for good.
    """
    Case = apps.get_model("cases", "Case")
    Case.objects.exclude(external_ref="").filter(plan_date__isnull=True).update(
        plan_date=Coalesce(TruncDate("assigned_at"), TruncDate("created_at"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='plan_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_plan_date, migrations.RunPython.noop),
    ]
