# Generated by Django 5.2.14 on 2026-08-26 05:39

from django.db import migrations, models


def number_the_blank_ones(apps, schema_editor):
    """Give a number to any case left holding the blank placeholder.

    save() inserts a placeholder and fills it in on a second write. When that
    second write did not happen — a crash, a rolled-back request — the row kept
    the EMPTY STRING, and because case_number is unique that one row then made
    every later insert fail: "duplicate key value violates unique constraint
    ... Key (case_number)=()". One stuck row was enough to stop the whole sync.

    Runs AFTER the column is made nullable, so "" can be replaced safely, and
    numbers each row from its own pk exactly as save() would have.
    """
    Case = apps.get_model("cases", "Case")
    for pk in list(
        Case.objects.filter(case_number__in=["", None]).values_list("pk", flat=True)
    ):
        Case.objects.filter(pk=pk).update(case_number=f"OC-{pk:06d}")


def do_nothing(apps, schema_editor):
    """Nothing to undo: the rows are simply numbered, which is what they wanted."""


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_release_orphaned_completion_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(number_the_blank_ones, do_nothing),
    ]
