# Generated by Django 5.2.14 on 2026-08-31 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_case_number'),
        ('employees', '0015_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnappedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('points', models.JSONField(blank=True, default=list)),
                ('last_ping_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapped_tracks', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['engineer', 'day'], name='cases_snapp_enginee_0a6bea_idx')],
                'constraints': [models.UniqueConstraint(fields=('engineer', 'day'), name='one_snapped_track_per_engineer_day')],
            },
        ),
    ]
