# Generated by Django 5.2.14 on 2026-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_snappedtrack'),
        ('employees', '0015_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='Percent, 0-100, as the phone reported it', null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='client_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='is_charging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationping',
            name='received_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='locationping',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key__isnull', False)), fields=('engineer', 'client_key'), name='one_ping_per_client_key'),
        ),
    ]
