# Generated by Django 5.2.14 on 2026-09-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_locationping_battery_level_locationping_client_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='punch_in_accuracy',
            field=models.FloatField(blank=True, help_text='Metres, as the phone reported', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='punch_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='punch_in_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='punch_out_accuracy',
            field=models.FloatField(blank=True, help_text='Metres, as the phone reported', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='punch_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='punch_out_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
