# Generated by Django 5.2.14 on 2026-09-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_case_punch_in_accuracy_case_punch_in_lat_and_more'),
        ('employees', '0016_employee_flexible_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('assigned', models.IntegerField(default=0)),
                ('attended', models.IntegerField(default=0)),
                ('closed', models.IntegerField(default=0)),
                ('month_closed', models.IntegerField(default=0)),
                ('daily_target', models.IntegerField(default=0)),
                ('monthly_target', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='employees.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['as_of'], name='cases_engin_as_of_d241d6_idx')],
            },
        ),
    ]
