# Generated by Django 5.2.14 on 2026-09-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_engineerscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='after_gap',
            field=models.BooleanField(default=False),
        ),
    ]
