# Generated by Django 5.2.14 on 2026-09-07 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_locationping_after_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_key', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lon_key', models.DecimalField(decimal_places=4, max_digits=9)),
                ('address', models.CharField(max_length=300)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lat_key', 'lon_key'), name='one_name_per_place')],
            },
        ),
    ]
