# Generated by Django 5.2.14 on 2026-09-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_placename'),
        ('employees', '0016_employee_flexible_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(db_index=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('punch_in_lat', models.FloatField(blank=True, null=True)),
                ('punch_in_lon', models.FloatField(blank=True, null=True)),
                ('punch_in_accuracy', models.FloatField(blank=True, help_text='Metres, as the phone reported', null=True)),
                ('punch_out_lat', models.FloatField(blank=True, null=True)),
                ('punch_out_lon', models.FloatField(blank=True, null=True)),
                ('punch_out_accuracy', models.FloatField(blank=True, help_text='Metres, as the phone reported', null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='cases.case')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_visits', to='employees.employee')),
            ],
            options={
                'ordering': ['plan_date', 'id'],
                'indexes': [models.Index(fields=['engineer', 'plan_date'], name='cases_casev_enginee_e75e49_idx'), models.Index(fields=['case', '-plan_date'], name='cases_casev_case_id_d25bb6_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'plan_date'), name='one_visit_per_case_per_day')],
            },
        ),
    ]
