# Generated by Django 5.2.14 on 2026-06-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0003_payslip_deduction_insurance_payslip_employer_epf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Chennai', 'Chennai'), ('Vellore', 'Vellore'), ('Salem', 'Salem'), ('Kanchipuram', 'Kanchipuram'), ('Hosur', 'Hosur')], max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'branch'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
    ]
