# Generated by Django 5.2.14 on 2026-07-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0004_branchfinancial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='off_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
