# Generated by Django 5.2.14 on 2026-07-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0005_payslip_off_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='lop_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='off_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='paid_days',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
    ]
