# Generated by Django 5.2.14 on 2026-08-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0006_alter_payslip_lop_days_alter_payslip_off_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='casual_leave_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
