# Generated by Django 5.2.14 on 2026-08-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0007_payslip_casual_leave_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='casual_leave_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
