# Generated by Django 5.2.14 on 2026-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0008_payslip_casual_leave_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='special_work_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='special_work_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
