# Generated by Django 5.2.14 on 2026-10-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollpayslip', '0011_payslips_start_unsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='manual_overrides',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='structure',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
