# Generated by Django 5.2.14 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
