# Generated by Django 5.2.14 on 2026-06-30 09:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_sections',
            field=models.JSONField(blank=True, default=authentication.models.default_sections),
        ),
    ]
