# Generated by Django 5.2.14 on 2026-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_allowed_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_branch',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
