# Generated by Django 5.2.14 on 2026-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_app_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_app_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
