# Generated by Django 5.2.14 on 2026-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_first_app_login_at_user_last_app_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='app_version_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
