# Generated by Django 5.2.14 on 2026-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='request_type',
            field=models.CharField(choices=[('salary_advance', 'Salary advance'), ('petrol_advance', 'Petrol advance'), ('expense', 'Expense claim'), ('other_amount', 'Other amount'), ('report', 'Report / message')], db_index=True, max_length=20),
        ),
    ]
