# Generated by Django 5.2.14 on 2026-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_onboarding_doc_aadhaar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('segment', models.CharField(choices=[('Combo', 'Combo'), ('PC', 'PC'), ('Print', 'Print'), ('CCTV', 'CCTV'), ('Networking', 'Networking')], default='Combo', max_length=50)),
                ('previous_company', models.CharField(blank=True, max_length=255, null=True)),
                ('last_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('expecting_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action', models.CharField(choices=[('RNR', 'RNR'), ('In Progress', 'In Progress'), ('Offer Shared', 'Offer Shared'), ('Waiting For Acceptance', 'Waiting For Acceptance'), ('Waiting For Joining Date', 'Waiting For Joining Date'), ('Salary Discussion', 'Salary Discussion'), ('Rejected', 'Rejected'), ('Decline', 'Decline')], default='In Progress', max_length=50)),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='hiring/salary_slips/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='hiring/offer_letters/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='hiring/bank_statements/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='hiring/resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
