# Generated by Django 5.2.14 on 2026-08-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Relieved', 'Relieved')], db_index=True, default='Active', max_length=20),
        ),
    ]
