# Generated by Django 5.2.14 on 2026-08-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_onboarding_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
