# Generated by Django 5.2.14 on 2026-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_candidate_email_candidate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='onboarding_docs/agreement/'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='category',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer'), ('Vendor', 'Vendor')], db_index=True, default='Employee', max_length=20),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='contact_person_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='gst_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='rate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('Per case', 'Per case'), ('Per day', 'Per day'), ('Per hour', 'Per hour'), ('Monthly', 'Monthly'), ('Per job quote', 'Per job quote')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
