# Generated by Django 5.2.14 on 2026-10-08 10:27

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_onboarding_agreement_onboarding_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Employee', 'Employee'), ('Freelancer', 'Freelancer'), ('Vendor', 'Vendor')], max_length=20, unique=True)),
                ('token', models.CharField(db_index=True, default=onboarding.models.new_invite_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='onboarding',
            name='source',
            field=models.CharField(choices=[('Office', 'Office'), ('Self', 'Self')], db_index=True, default='Office', max_length=20),
        ),
    ]
