# Generated by Django 5.2.14 on 2026-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='intime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
