# Generated by Django 5.2.14 on 2026-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_closed_out',
            field=models.BooleanField(default=False),
        ),
    ]
